// Source: React Bits (David Haz), MIT + Commons Clause License Condition v1.0.
// https://github.com/DavidHDev/react-bits
import { useCallback, useEffect, useRef, type ReactNode } from "react";

type Spark = { x: number; y: number; angle: number; startTime: number };
export default function ClickSpark({ sparkColor = "#fff", sparkSize = 10, sparkRadius = 15, sparkCount = 8, duration = 400, easing = "ease-out", extraScale = 1, children }: { sparkColor?: string; sparkSize?: number; sparkRadius?: number; sparkCount?: number; duration?: number; easing?: "linear" | "ease-in" | "ease-out" | "ease-in-out"; extraScale?: number; children?: ReactNode }) {
  const canvasRef = useRef<HTMLCanvasElement>(null); const sparksRef = useRef<Spark[]>([]);
  useEffect(() => { const canvas = canvasRef.current; const parent = canvas?.parentElement; if (!canvas || !parent) return; let timeout: ReturnType<typeof setTimeout>; const resize = () => { const { width, height } = parent.getBoundingClientRect(); canvas.width = width; canvas.height = height; }; const observer = new ResizeObserver(() => { clearTimeout(timeout); timeout = setTimeout(resize, 100); }); observer.observe(parent); resize(); return () => { observer.disconnect(); clearTimeout(timeout); }; }, []);
  const ease = useCallback((time: number) => easing === "linear" ? time : easing === "ease-in" ? time * time : easing === "ease-in-out" ? time < .5 ? 2 * time * time : -1 + (4 - 2 * time) * time : time * (2 - time), [easing]);
  useEffect(() => { const canvas = canvasRef.current; const context = canvas?.getContext("2d"); if (!canvas || !context) return; let frame = 0; const draw = (now: number) => { context.clearRect(0, 0, canvas.width, canvas.height); sparksRef.current = sparksRef.current.filter((spark) => { const elapsed = now - spark.startTime; if (elapsed >= duration) return false; const progress = ease(elapsed / duration); const distance = progress * sparkRadius * extraScale; const length = sparkSize * (1 - progress); context.strokeStyle = sparkColor; context.lineWidth = 2; context.beginPath(); context.moveTo(spark.x + distance * Math.cos(spark.angle), spark.y + distance * Math.sin(spark.angle)); context.lineTo(spark.x + (distance + length) * Math.cos(spark.angle), spark.y + (distance + length) * Math.sin(spark.angle)); context.stroke(); return true; }); frame = requestAnimationFrame(draw); }; frame = requestAnimationFrame(draw); return () => cancelAnimationFrame(frame); }, [duration, ease, extraScale, sparkColor, sparkRadius, sparkSize]);
  return <div className="click-spark" onClick={(event) => { const rect = canvasRef.current?.getBoundingClientRect(); if (!rect) return; const now = performance.now(); sparksRef.current.push(...Array.from({ length: sparkCount }, (_, index) => ({ x: event.clientX - rect.left, y: event.clientY - rect.top, angle: 2 * Math.PI * index / sparkCount, startTime: now }))); }}><canvas ref={canvasRef} /><>{children}</></div>;
}
