// Source: React Bits (David Haz), MIT + Commons Clause License Condition v1.0.
// https://github.com/DavidHDev/react-bits
import { useEffect, useRef, useState, type HTMLAttributes, type ReactNode } from "react";

export default function Magnet({ children, padding = 100, disabled = false, magnetStrength = 2, activeTransition = "transform 0.3s ease-out", inactiveTransition = "transform 0.5s ease-in-out", wrapperClassName = "", innerClassName = "", ...props }: HTMLAttributes<HTMLDivElement> & { children: ReactNode; padding?: number; disabled?: boolean; magnetStrength?: number; activeTransition?: string; inactiveTransition?: string; wrapperClassName?: string; innerClassName?: string }) {
  const [isActive, setIsActive] = useState(false); const [position, setPosition] = useState({ x: 0, y: 0 }); const magnetRef = useRef<HTMLDivElement>(null);
  useEffect(() => { if (disabled) { setPosition({ x: 0, y: 0 }); return; } const handleMouseMove = (event: MouseEvent) => { const element = magnetRef.current; if (!element) return; const { left, top, width, height } = element.getBoundingClientRect(); const centerX = left + width / 2; const centerY = top + height / 2; if (Math.abs(centerX - event.clientX) < width / 2 + padding && Math.abs(centerY - event.clientY) < height / 2 + padding) { setIsActive(true); setPosition({ x: (event.clientX - centerX) / magnetStrength, y: (event.clientY - centerY) / magnetStrength }); } else { setIsActive(false); setPosition({ x: 0, y: 0 }); } }; window.addEventListener("mousemove", handleMouseMove); return () => window.removeEventListener("mousemove", handleMouseMove); }, [disabled, magnetStrength, padding]);
  return <div ref={magnetRef} className={wrapperClassName} style={{ position: "relative", display: "inline-block" }} {...props}><div className={innerClassName} style={{ transform: `translate3d(${position.x}px, ${position.y}px, 0)`, transition: isActive ? activeTransition : inactiveTransition, willChange: "transform" }}>{children}</div></div>;
}
